# Generated by Django 4.1 on 2022-09-05 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('checkin_dtime', models.DateTimeField()),
                ('checkout_dtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Hotel-Image', validators=[django.core.validators.validate_image_file_extension])),
                ('total_rooms', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
