# Generated by Django 3.2.10 on 2022-09-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220905_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked',
            field=models.BooleanField(default=True),
        ),
    ]
